version: "3.8"

x-common-env: &common-env
  DISABLE_PROFILER: 1
  DISABLE_TRACING: 1
  DISABLE_STATS: 1

services:

  frontend:
    build: ./src/frontend
    ports:
      - "8080:8080"
    environment:
      <<: *common-env
      PORT: 8080
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
      CURRENCY_SERVICE_ADDR: currencyservice:7000
      CART_SERVICE_ADDR: cartservice:7070
      CHECKOUT_SERVICE_ADDR: checkoutservice:5050
      SHIPPING_SERVICE_ADDR: shippingservice:50051
      PAYMENT_SERVICE_ADDR: paymentservice:50051
      RECOMMENDATION_SERVICE_ADDR: recommendationservice:8080
      EMAIL_SERVICE_ADDR: emailservice:5000
      AD_SERVICE_ADDR: adservice:9555
    depends_on:
      - productcatalogservice
      - currencyservice
      - cartservice
      - checkoutservice
      - paymentservice
      - shippingservice
      - emailservice
      - recommendationservice

  productcatalogservice:
    build: ./src/productcatalogservice
    environment:
      <<: *common-env
      PORT: 3550

  currencyservice:
    build: ./src/currencyservice
    environment:
      <<: *common-env
      PORT: 7000

  cartservice:
    build:
      context: ./src/cartservice/src
    environment:
      <<: *common-env
      ASPNETCORE_URLS: http://+:7070
      REDIS_ADDR: redis:6379
    depends_on:
      - redis

  checkoutservice:
    build: ./src/checkoutservice
    environment:
      <<: *common-env
      PORT: 5050
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
      SHIPPING_SERVICE_ADDR: shippingservice:50051
      PAYMENT_SERVICE_ADDR: paymentservice:50051
      CURRENCY_SERVICE_ADDR: currencyservice:7000
      CART_SERVICE_ADDR: cartservice:7070
      EMAIL_SERVICE_ADDR: emailservice:5000
    depends_on:
      - productcatalogservice
      - shippingservice
      - paymentservice
      - currencyservice
      - cartservice
      - emailservice

  paymentservice:
    build: ./src/paymentservice
    environment:
      <<: *common-env
      PORT: 50051

  shippingservice:
    build: ./src/shippingservice
    environment:
      <<: *common-env
      PORT: 50051

  adservice:
    build: ./src/adservice
    environment:
      <<: *common-env
      PORT: 9555

  emailservice:
    build: ./src/emailservice
    environment:
      <<: *common-env
      PORT: 5000

  recommendationservice:
    build: ./src/recommendationservice
    environment:
      <<: *common-env
      PORT: 8080
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
    depends_on:
      - productcatalogservice

  redis:
    image: redis:7
    ports:
      - "6379:6379"
